workflows:
  ios-local-build:
    name: iOS Local Archive
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Archive only
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/App.xcarchive
